export enum PARAMETROS {
  MEDICACION_VIAS = 'MEDICACION_VIAS',
  MEDICACION_VARIANTES = 'MEDICACION_VARIANTES',
  IDENTIFICACIONES = 'IDENTIFICACIONES',
  FRECUENCIAS_MEDICACION = 'FRECUENCIAS_MEDICACION',
  MEDICACION_TIPOS_SUMINISTRACION = 'MEDICACION_TIPOS_SUMINISTRACION',
}
